name: Close Issues on Develop Merge

on:
  pull_request:
    types: [closed]

jobs:
  close-linked-issues:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close issues linked in PR description
        uses: actions/github-script@v6
        with:
          script: |
            const prBody = context.payload.pull_request.body;
            const issueRegex = /(closes|closed|fixes|fixed|resolves|resolved)\s+#(\d+)/gi;
            const issuesToClose = new Set();
            let match;
            while ((match = issueRegex.exec(prBody)) !== null) {
              issuesToClose.add(parseInt(match[2]));
            }
            for (const issueNumber of issuesToClose) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                state: 'closed'
              });
            }