name: Unity PlayMode Tests

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  playmode-tests:
    name: Run Unity PlayMode Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Unity packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/unity3d
            ~/.local/share/unity3d
          key: Library

      - name: Set up Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2021.3.45f1

      - name: Run PlayMode Tests
        uses: game-ci/unity-test-runner@v2
        with:
          unityVersion: 2021.3.45f1
          testMode: PlayMode
          projectPath: ./
          artifactsPath: artifacts
          coverageOptions: 'generateAdditionalMetrics'

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: PlayMode Test Results
          path: artifacts
